FROM nodered/node-red:latest-minimal
RUN npm install \
    flat \
    node-red-contrib-flat \
    node-red-dashboard \
    node-red-contrib-python-function \
    node-red-contrib-influxdb \
    node-red-node-cf-cloudant \
    node-red-contrib-md5 \
    node-red-node-ui-table \
    node-red-node-ui-list \
    node-red-contrib-ui-upload \
    node-red-contrib-re-postgres \
    node-red-contrib-file-upload \
    @ragrug/ragrug-nodered
