{
 "title": "Heating",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "tag5selectorA", "label": "tag5selectorA", "query": "${VAR_TAG5SELECTORA}" },
   { "name": "tag5selectorB", "label": "tag5selectorA", "query": "${VAR_TAG5SELECTORB}" },
   { "name": "tag4selectorB", "label": "tag5selectorA", "query": "${VAR_TAG4SELECTORB}" },
   { "name": "tag4selectorA", "label": "tag5selectorA", "query": "${VAR_TAG4SELECTORA}" },
   { "name": "fieldA", "label": "fieldA", "query": "${VAR_FIELDA}" },
   { "name": "fieldB", "label": "fieldB", "query": "${VAR_FIELDB}" }
  ]
 },
 "panels": [
  {
   "title": "r0/inflow",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "celsius", "label": "Temperature" }
   ],
   "targets": [
    {
     "alias": "Temperature",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "heating",
     "query": "SELECT moving_average(mean(\"temperature\"), 10) FROM \"data30d\".\"heating\" WHERE (\"tag4\" = 'r0' AND \"tag5\" = 'inflow') AND time > now() - 15m GROUP BY time(10s) fill(previous)",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       }
      ]
     ],
     "tags": [
      { "key": "tag4", "operator": "=", "value": "r0" },
      { "condition": "AND", "key": "tag5", "operator": "=", "value": "inflow" }
     ]
    },
    {
     "alias": "Flowrate",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "heating",
     "select": [
      [
       { "params": [ "flowrate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       }
      ]
     ],
     "tags": [
      { "key": "tag4", "operator": "=", "value": "r0" },
      { "condition": "AND", "key": "tag5", "operator": "=", "value": "inflow" }
     ]
    }
   ]
  },
  { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 } },
  {
   "title": "r0/backflow",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "celsius", "label": "Temperature" }
   ],
   "targets": [
    {
     "alias": "Temperature",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "heating",
     "query": "SELECT moving_average(mean(\"temperature\"), 10) FROM \"data30d\".\"heating\" WHERE (\"tag4\" = 'r0' AND \"tag5\" = 'inflow') AND time > now() - 15m GROUP BY time(10s) fill(previous)",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       }
      ]
     ],
     "tags": [
      { "key": "tag4", "operator": "=", "value": "r0" },
      { "condition": "AND", "key": "tag5", "operator": "=", "value": "backflow" }
     ]
    },
    {
     "alias": "Flowrate",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "heating",
     "select": [
      [
       { "params": [ "flowrate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       }
      ]
     ],
     "tags": [
      { "key": "tag4", "operator": "=", "value": "r0" },
      { "condition": "AND", "key": "tag5", "operator": "=", "value": "backflow" }
     ]
    }
   ]
  },
  {
   "title": "$tag4selectorA/$tag5selectorA/$fieldA vs $tag4selectorB/$tag5selectorB/$fieldB",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag4selectorA/$tag5selectorA/$fieldA",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "heating",
     "query": "SELECT moving_average(mean(\"temperature\"), 10) FROM \"data30d\".\"heating\" WHERE (\"tag4\" = 'r0' AND \"tag5\" = 'inflow') AND time > now() - 15m GROUP BY time(10s) fill(previous)",
     "select": [
      [
       { "params": [ "$fieldA" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       }
      ]
     ],
     "tags": [
      { "key": "tag4", "operator": "=", "value": "$tag4selectorA" },
      { "condition": "AND", "key": "tag5", "operator": "=", "value": "$tag5selectorA" }
     ]
    },
    {
     "alias": "$tag4selectorB/$tag5selectorB/$fieldB",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "heating",
     "select": [
      [
       { "params": [ "$fieldB" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       }
      ]
     ],
     "tags": [
      { "key": "tag4", "operator": "=", "value": "$tag4selectorB" },
      { "condition": "AND", "key": "tag5", "operator": "=", "value": "$tag5selectorB" }
     ]
    }
   ]
  },
  {
   "title": "notebook/body",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "percent", "label": "Load" }
   ],
   "targets": [
    {
     "alias": "CPU Load",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "heating",
     "query": "SELECT moving_average(mean(\"temperature\"), 10) FROM \"data30d\".\"heating\" WHERE (\"tag4\" = 'r0' AND \"tag5\" = 'inflow') AND time > now() - 15m GROUP BY time(10s) fill(previous)",
     "select": [
      [
       { "params": [ "cpuload" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       }
      ]
     ],
     "tags": [
      { "key": "tag4", "operator": "=", "value": "notebook" },
      { "condition": "AND", "key": "tag5", "operator": "=", "value": "body" }
     ]
    },
    {
     "alias": "CPU Temp",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "heating",
     "select": [
      [
       { "params": [ "cputemp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       }
      ]
     ],
     "tags": [
      { "key": "tag4", "operator": "=", "value": "notebook" },
      { "condition": "AND", "key": "tag5", "operator": "=", "value": "body" }
     ]
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 16 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "tag1" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "heating",
     "query": "SELECT mean(\"humidity\") FROM \"heating\" WHERE $timeFilter GROUP BY time(1m), \"tag1\" fill(none)",
     "select": [
      [
       { "params": [ "preasure" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "40" ], "type": "moving_average" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Heat distribution",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 16 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "heating",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "so/main",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "alias": "Voltage",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "heating",
     "query": "SELECT moving_average(mean(\"temperature\"), 10) FROM \"data30d\".\"heating\" WHERE (\"tag4\" = 'r0' AND \"tag5\" = 'inflow') AND time > now() - 15m GROUP BY time(10s) fill(previous)",
     "select": [
      [
       { "params": [ "voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       }
      ]
     ],
     "tags": [
      { "key": "tag4", "operator": "=", "value": "s0" },
      { "condition": "AND", "key": "tag5", "operator": "=", "value": "main" }
     ]
    },
    {
     "alias": "Frequency",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "heating",
     "select": [
      [
       { "params": [ "frequenzy" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       }
      ]
     ],
     "tags": [
      { "key": "tag4", "operator": "=", "value": "s0" },
      { "condition": "AND", "key": "tag5", "operator": "=", "value": "main" }
     ]
    }
   ]
  },
  {
   "title": "S003",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "heating",
     "query": "SELECT moving_average(mean(\"temperature\"), 10) FROM \"data30d\".\"heating\" WHERE (\"tag5\" = 's003') AND time > now() - 15m GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       }
      ]
     ],
     "tags": [
      { "key": "tag5", "operator": "=", "value": "s003" }
     ]
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "tag1" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "heating",
     "query": "SELECT mean(\"humidity\") FROM \"heating\" WHERE $timeFilter GROUP BY time(1m), \"tag1\" fill(none)",
     "select": [
      [
       { "params": [ "humidity" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "40" ], "type": "moving_average" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Current Temperature",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 5, "x": 12, "y": 31 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "tag1" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "heating",
     "query": "SELECT moving_average(mean(\"temperature\"), 40) FROM \"heating\" WHERE $timeFilter GROUP BY time(1m), \"tag1\" fill(none)",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "5" ], "type": "moving_average" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 31 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "tag1" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "heating",
     "query": "SELECT moving_average(mean(\"temperature\"), 40) FROM \"heating\" WHERE $timeFilter GROUP BY time(1m), \"tag1\" fill(none)",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "40" ], "type": "moving_average" }
      ]
     ]
    }
   ]
  },
  {
   "title": "All Time Data",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "tag1" ], "type": "tag" },
      { "params": [ "tag2" ], "type": "tag" },
      { "params": [ "tag3" ], "type": "tag" }
     ],
     "measurement": "heating",
     "query": "SELECT count(\"ts\") FROM \"data30d\".\"heating\" GROUP BY \"tag1\", \"tag2\", \"tag3\"",
     "select": [
      [
       { "params": [ "ts" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  { "title": "News", "type": "news", "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 } }
 ]
}